---
- hosts: all
  roles:
    - setup
    - geerlingguy.postgresql
    - idealista.airflow-role
    - efs
    - {role: nginx, when: airflow_ssl_enabled | bool}
    #- {role: redis, when: airflow_executor == 'CeleryExecutor'}

  vars:
    # Airflow
    airflow_user: airflow
    airflow_group: airflow
    airflow_executor: SequentialExecutor
    airflow_pip_executable: /usr/bin/pip3
    airflow_required_python_packages:
      - {name: pyasn1, version: 0.4.4}
      - {name: werkzeug, version: 0.16.0}
      - {name: psycopg2-binary}
    airflow_version: 1.10.10
    airflow_load_examples: False

    # EFS
    mount_path: "/etc/airflow/dags"
    file_system_id: "{{ file_system_id }}"
    
    # SSL
    enable_airflow_ssl: false

    # Postgres backend DB
    airflow_database_conn: postgresql+psycopg2://airflow:airflow@localhost:5432/airflow
    postgresql_databases:
      - name: airflow
    postgresql_users:
      - name: airflow
        password: airflow